name: Build & Test

on:
  push:
    branches: [ "main" ]
  pull_request:

env:
  CARGO_TERM_COLOR: always
  ETH_HTTP_RPC: https://eth.llamarpc.com

jobs:
  test:
    name: Test ${{ matrix.rust }} ${{ matrix.flags }}
    timeout-minutes: 30
    runs-on: "ubuntu-latest"
    strategy:
      fail-fast: false
      matrix:
        rust:
          - "stable"
          - "nightly"
        flags:
          # Default features
          - ""
          # All features
          - "--all-features"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
      - name: Install cargo-nextest
        uses: taiki-e/install-action@nextest
      - name: Build
        run: cargo build --workspace ${{ matrix.flags }}
      - name: Test
        run: cargo nextest run --workspace ${{ matrix.flags }}